manifest:
  remotes:
    - name: urob
      url-base: https://github.com/urob
    - name: ftc
      url-base: https://github.com/ftc
  projects:
    - name: zmk
      remote: ftc
      revision: main
      import: app/west.yml
  self:
    path: config
